name: jest test and linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jestlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 19
        uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Install dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint:fix
      - name: Test with Jest
        run: npm run test .test
